package com.usercreate.usercreate.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "customer")
public class Customer {

    @DynamoDBHashKey(attributeName = "customerId")
    private String customerId;
    
    
    @DynamoDBAttribute(attributeName = "password")
    private String password;
    
    @DynamoDBAttribute(attributeName = "title")
    private String title;
    
    @DynamoDBAttribute(attributeName = "firstName")
    private String firstName;
    
    @DynamoDBAttribute(attributeName = "lastName")
    private String lastName;
    
    @DynamoDBAttribute(attributeName = "postcode")
    private int postcode;
    
    @DynamoDBAttribute(attributeName = "suburb")
    private String suburb;
    
    @DynamoDBAttribute(attributeName = "state")
    private String state;
    
    @DynamoDBAttribute(attributeName = "fullAddress")
    private String fullAddress;
    
    @DynamoDBAttribute(attributeName = "mobileNumber")
    private int mobileNumber;
    
   

    public String getCustomerId() {
        return customerId;
    }

    public void setCustomerId(String customerId) {
    	//String string = "12345.15";
        boolean numeric = true;

        try {
            Double num = Double.parseDouble(customerId);
        } catch (NumberFormatException e) {
            numeric = false;
        }

        if(numeric) {
        	
            System.out.println(customerId + " is a number");
            
            this.customerId = customerId;
            }
        else {
        	    System.out.println(customerId + " is not a number");
            }
    
        
    }

    
    
    
    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    
    
    public String getLastName() 
    {
        return lastName;
    }

    public void setLastName(String lastName) 
    
    {
        this.lastName = lastName;
        
    }
    
    public int getMobileNumber() {
    	
    	/*boolean numeric = true;

        try {
            Double num = Double.parseDouble(mobileNumber);
        } catch (NumberFormatException e) {
            numeric = false;
        }

        if(numeric) {
        	return mobileNumber;
            }
        else {
        	this.mobileNumber = "null";   
        	return mobileNumber;
        	}
        */
    	return mobileNumber;
    }

    public void setMobileNumber(int mobileNumber) {
    	
    	
        this.mobileNumber = mobileNumber;
    }
    
    

    public int getPostCode() {
        return postcode;
    }

    public void setPostCode(int postcode) {
        this.postcode = postcode;
    }
    
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }
    
    public String getSubUrb() {
        return suburb;
    }

    public void setSubUrb(String suburb) {
        this.suburb = suburb;
    }
    
    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }
    
    public String getFullAddress() {
        return fullAddress;
    }

    public void setFullAddress(String fullAddress) {
        this.fullAddress = fullAddress;
    }

}

